version: '2.1'
services:
  hn_manticore:
    build:
      context: .
      dockerfile: Dockerfile_manticore
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9306
    container_name: "hn_manticore"

  hn_sphinx:
    build:
      context: .
      dockerfile: Dockerfile_sphinx
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9306
    container_name: "hn_sphinx"
  indexer:
    build:
      context: .
      dockerfile: Dockerfile_indexer
    container_name: "indexer"
    volumes:
      - /home/mis/data/csv/:/root/csv/

    depends_on:
      - hn_manticore
      - hn_sphinx

#  hn_test:
#    build:
#      context: test
#    container_name: "hn_test"
#
#    depends_on:
#      - indexer


